---
title: "Research"
---

My research revolves around the question of how to model and quantify the variability of anatomical shapes, and how to use these models as priors in image analysis and prediction tasks. I am mainly interested in generative approaches, 
using Bayesian approaches and the analysis-by-synthesis paradigm, with the goal of obtaining both useful prediction of partially observed structures as well as proper uncertainty quantification. 

An important part of my research has always been to complement the algorithmic and theoretical models with 
software that can be used in real world applications. To this end, I am one of the core-developers and 
maintainers of the [Scalismo](https://scalismo.rog) software, and open source software framework for 
model based shape and image analysis. This framework has been used in a wide variety of commercial applications and 
is since commercially supported by the company [Shapemeans](https://shapmeans.com).

### Selected publications

A full list of my publications can be found on my [Google scholar profile](https://scholar.google.com/citations?user=6SbtjIIAAAAJ&hl=en&oi=ao).


#### Modelling

* Dölz, J., Gerig, T., Lüthi, M., Harbrecht, H., & Vetter, T. (2019). **Error-controlled model approximation for Gaussian process morphable models.** *Journal of Mathematical Imaging and Vision*

* Lüthi, M., Gerig, T., Jud, C., & Vetter, T. (2017). **Gaussian process morphable models**, *IEEE transactions on pattern analysis and machine intelligence (PAMI)*

* Albrecht, T, Lüthi M., Gerig T., Vetter T. (2013) **Posterior shape models**, *Medical image analysis*

* Lüthi M., Albrecht, T, Vetter T. (2009) **Building shape models from lousy data**, *Intl. Conference on Medical Image Computing and Computer-Assisted Intervention (MICCAI)*


#### Model Fitting, registration and uncertainty quantification

* Madsen, D., Morel-Forster, A., Kahr, P., Rahbani, D., Vetter, T., & Lüthi, M. (2020). **A closest point proposal for MCMC-based probabilistic surface registration**, *Computer Vision–ECCV 2020*

* Madsen, D., Vetter, T., & Lüthi, M. (2019). **Probabilistic surface reconstruction with unknown correspondence**, *Uncertainty for Safe Utilization of Machine Learning in Medical Imaging and Clinical Image-Based Procedures*

* Gerig, T., Shahim, K., Reyes, M., Vetter, T., & Lüthi, M. (2014). **Spatially varying registration using Gaussian processes**, *Medical Image Computing and Computer-Assisted Intervention*

* Albrecht, T., Lüthi, M., & Vetter, T. (2008, June). **A statistical deformation prior for non-rigid image and shape registration**, *Conference on Computer Vision and Pattern Recognition*


#### Medical and other applications

* Kramer, D., Van der Merwe, J., & Lüthi, M. (2022). **A combined active shape and mean appearance model for the reconstruction of segmental bone loss**, *Medical Engineering & Physics*

* Ebert, L. C., Rahbani, D., Lüthi, M., Thali, M. J., Christensen, A. M., & Fliss, B. (2022). **Reconstruction of full femora from partial bone fragments for anthropological analyses using statistical shape modeling**. *Forensic Science International*

* Schmutz, B., Lüthi, M., Schmutz-Leong, Y. K., Shulman, R., & Platt, S. (2021). **Morphological analysis of Gissane’s angle utilising a statistical shape model of the calcaneus.** Archives of orthopaedic and trauma surgery, 141, 937-945.

* Madsen, D., Lüthi, M., Schneider, A., & Vetter, T. (2018). **Probabilistic joint face-skull modelling for facial reconstruction**, *Proceedings of the IEEE conference on computer vision and pattern recognition*.

* Mauler, F., Langguth, C., Schweizer, A., Vlachopoulos, L., Gass, T., Lüthi, M., & Fürnstahl, P. (2017). **Prediction of normal bone anatomy for the planning of corrective osteotomies of malunited forearm bones using a three‐dimensional statistical shape model**, Journal of Orthopaedic Research

#### Other topics

* Meyer, B., Stadelmann, T., & Lüthi, M. (2024). **ScalaGrad: a statically typed automatic differentiation library for safer data science.**, *IEEE Swiss Conference on Data Science (SDS), Zurich, Switzerland*

* Lüthi, M., Nadjm-Tehrani, S., & Curescu, C. (2006, April). **Comparative study of price-based resource allocation algorithms for ad hoc networks**, *IEEE International Parallel & Distributed Processing Symposium*

* Bergkvist, A., Damaschke, P., Lüthi, M., Bennett, K. P., & Parrado-Hernández, E. (2006). **Linear Programs for Hypotheses Selection in Probabilistic Inference Models**, *Journal of Machine Learning Research*

