---
title: "Teaching"
---

### Teaching philosophy

I believe that what our job as educators is to create an environment in which 
learning can take place. The focus of our attention should be to enable and facilitate learning
rather than focusing narrowly on teaching. As an educator, I would like to provide a course environment that encourages the students to actively explore and experiment with the material and to make the 
barriers to experimentation as low as possible. 

Being involved in all aspects of the course and engaging with students during the learning process, is crucial. Only by interacting with students we can understand the needs, the difficulties 
they face and from which parts they draw most value. This is especially important in the currently, rapidly changing
teaching environment. More direct contact also establishes trust between students and teachers, which 
is most important for a productive learning environment. 

Technology is evolving at a rapid pace and with it come great opportunities but also possible impediments for student learning. I see it as an important part of my role to engage with new technologies and guide students regarding their use in the learning process. 


### Current courses

- Informatik I (with A. Streich) [(Course directory)](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=182735&semkez=2024W&ansicht=LEHRVERANSTALTUNGEN&lang=de)
- Informatik II (with Manuela Fischer) [(Course directory)](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=188270&semkez=2025S&ansicht=LEHRVERANSTALTUNGEN&lang=de)
- Software Engineering (with H. Lehner and M Schwerhoff) [(Course directory)](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=181757&semkez=2024W&ansicht=LEHRVERANSTALTUNGEN&lang=de)
- Data Science and Machine Learning (with A. Streich) [(Course directory)](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=190199&semkez=2025S&ansicht=LEHRVERANSTALTUNGEN&lang=de)
- Datenanalyse in der Physik (with A. Eichler, M. Kroner, C. Cotrini) [(Course directory)](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=178564&semkez=2024S&ansicht=LEHRVERANSTALTUNGEN&lang=de)

### Previous courses

At the university of Basel, I was teaching the following courses:

- Grundlagen der Programmierung (in Java)
- Einführung in die Programmierung (in Python)
- Software Engineering
- Probabilistic shape modelling
- Algorithmen und Datenstrukturen (with G. Röger)
- Machine intelligence (seminar, with V. Roth)
- Things I learned in computer science (seminar, with C. Tschudin)
- Programming with Monads (seminar, with C. Tschudin)
- Structure and interpretation of computer programs (seminar, with C. Tschudin)
- Machine learning for vision applications (with T. Vetter)

### Online courses 

To complement my classes at the University of Basel, I have developed the following online courses:

- [Einführung in die Programmierung (mit Python, German)](https://dmi-programming.dmi.unibas.ch/eidp/)
- [Grundlagen der Programmierung (mit Java, German)](https://dmi-programming.dmi.unibas.ch/gdp/)
- [Statistical shape modelling](https://shapemodelling.cs.unibas.ch/ssm-course/)

